import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner'

export default function Home({ data }) {
  console.log(data)

  const handleOnBannerBtnClick = () => {
    console.log('Hi, banner button')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>NEXT BREW</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleClick={handleOnBannerBtnClick}
        />
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const response = await fetch(`https://api.openbrewerydb.org/breweries`)
  const data = await response.json()

  return {
    props: {
      data,
    },
  }
}
